# CMake generated Testfile for 
# Source directory: C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master
# Build directory: C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-changelist__WIN32 "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-changelist")
set_tests_properties(test-changelist__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1198;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1264;add_backend_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-eof__WIN32 "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-eof")
set_tests_properties(test-eof__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1198;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1264;add_backend_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-fdleak__WIN32 "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-fdleak")
set_tests_properties(test-fdleak__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1198;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1264;add_backend_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-init__WIN32 "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-init")
set_tests_properties(test-init__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1198;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1264;add_backend_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-time__WIN32 "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-time")
set_tests_properties(test-time__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1198;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1264;add_backend_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-weof__WIN32 "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-weof")
set_tests_properties(test-weof__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1198;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1264;add_backend_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-dumpevents__WIN32 "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-dumpevents" "|" "C:/Users/TIMUR/AppData/Local/Programs/Python/Python36/python.exe" "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/test/check-dumpevents.py")
set_tests_properties(test-dumpevents__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1211;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1264;add_backend_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(regress__WIN32 "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/regress")
set_tests_properties(regress__WIN32 PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1" _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1233;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1264;add_backend_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(regress__WIN32_debug "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/regress")
set_tests_properties(regress__WIN32_debug PROPERTIES  ENVIRONMENT "EVENT_SHOW_METHOD=1;EVENT_DEBUG_MODE=1" _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1239;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1264;add_backend_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-ratelim__group_lim "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-ratelim" "-g" "30000" "-n" "30" "-t" "100" "--check-grouplimit" "1000" "--check-stddev" "100")
set_tests_properties(test-ratelim__group_lim PROPERTIES  _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1275;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-ratelim__con_lim "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-ratelim" "-c" "1000" "-n" "30" "-t" "100" "--check-connlimit" "50" "--check-stddev" "50")
set_tests_properties(test-ratelim__con_lim PROPERTIES  _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1284;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-ratelim__group_con_lim "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-ratelim" "-c" "1000" "-g" "30000" "-n" "30" "-t" "100" "--check-grouplimit" "1000" "--check-connlimit" "50" "--check-stddev" "50")
set_tests_properties(test-ratelim__group_con_lim PROPERTIES  _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1293;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
add_test(test-ratelim__group_con_lim_drain "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-build/bin/test-ratelim" "-c" "1000" "-g" "35000" "-n" "30" "-t" "100" "-G" "500" "--check-grouplimit" "1000" "--check-connlimit" "50" "--check-stddev" "50")
set_tests_properties(test-ratelim__group_con_lim_drain PROPERTIES  _BACKTRACE_TRIPLES "C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;1304;add_test;C:/Timur/Science/Учеба/Магистратура/C++/Cache Server/Cache-server-2/libevent-master/CMakeLists.txt;0;")
